// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBC-mwfGhvGc9qOiGEehIjkqTwHZLQQj9k',
    appId: '1:1090017856343:web:8684249a28da9c083bcc12',
    messagingSenderId: '1090017856343',
    projectId: 'simple-todo-app-58413',
    authDomain: 'simple-todo-app-58413.firebaseapp.com',
    storageBucket: 'simple-todo-app-58413.appspot.com',
    measurementId: 'G-38H1149R6V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoXFjsdTDf7QycZ28dsRrMs4VmdxJ4QXs',
    appId: '1:1090017856343:android:94d2ca71cb71fa553bcc12',
    messagingSenderId: '1090017856343',
    projectId: 'simple-todo-app-58413',
    storageBucket: 'simple-todo-app-58413.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_EoJfYMZ7IkMJmodwO2n-l5ZCch_4-yc',
    appId: '1:1090017856343:ios:32efb91531f8585c3bcc12',
    messagingSenderId: '1090017856343',
    projectId: 'simple-todo-app-58413',
    storageBucket: 'simple-todo-app-58413.appspot.com',
    iosClientId: '1090017856343-6n5e4bc0qcqfuihn7sjavsedtpc7n8k2.apps.googleusercontent.com',
    iosBundleId: 'com.example.simpleNotesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_EoJfYMZ7IkMJmodwO2n-l5ZCch_4-yc',
    appId: '1:1090017856343:ios:32efb91531f8585c3bcc12',
    messagingSenderId: '1090017856343',
    projectId: 'simple-todo-app-58413',
    storageBucket: 'simple-todo-app-58413.appspot.com',
    iosClientId: '1090017856343-6n5e4bc0qcqfuihn7sjavsedtpc7n8k2.apps.googleusercontent.com',
    iosBundleId: 'com.example.simpleNotesApp',
  );
}
